# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_procedure_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
