# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_element_numeric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='eid',
        ),
    ]
