# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-18 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_element_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together=set([('uuid', 'version')]),
        ),
    ]
