# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180218_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
