# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-22 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180219_2211'),
        ('api', '0022_device'),
    ]

    operations = [
    ]
