# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_event', to='api.Procedure')),
            ],
        ),
    ]
