# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-13 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180313_2240'),
        ('api', '0026_pushevent'),
    ]

    operations = [
    ]
