# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractelement',
            options={'ordering': ['concept', 'subroutine', 'display_index']},
        ),
        migrations.AlterModelOptions(
            name='subroutine',
            options={},
        ),
        migrations.AlterField(
            model_name='procedure',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
