# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181010_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
