name             'sana-protocol-builder'
maintainer       'Sana Protocol Builder'
description      'Installs/Configures sana-protocol-builder'
version          '1.0'
depends          'git'
depends          'ssh_known_hosts'
depends          'nginx'
depends          'supervisor'
depends          'virtualenvwrapper'
depends          'postgresql'
depends          'database'
