#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'git'
cookbook 'postgresql'
cookbook 'nginx'
cookbook 'python'
cookbook 'supervisor'
cookbook 'line'
cookbook 'virtualenvwrapper', :path => 'site-cookbooks/virtualenvwrapper'
cookbook 'sana-protocol-builder', :path => 'site-cookbooks/sana-protocol-builder'
